#version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: javi98/python-api-crud-template:1.0.0
    container_name: python-api-crud-template-app
    restart: unless-stopped
    # command: fastapi run app/main.py --port 8000 # Production mode
    # command: fastapi run app/main.py --port 8000 --reload # Development mode
    ports:
      - 8000:8000
    volumes:
      - ./:/code
    depends_on:
      - db
      - smtp

  db:
    image: mariadb:11.2.2
    container_name: python-api-crud-template-db
    restart: unless-stopped
    env_file: .env.dev # .env.dev | .env.prod
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  smtp:
    image: jcalonso/mailhog:v1.0.1
    container_name: python-api-crud-template-smtp
    restart: unless-stopped
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /home/mailhog
    volumes:
      - smtp-data:/home/mailhog

 
networks:
  python-api-crud-template:
    driver: bridge

volumes:
  db-data:
  smtp-data:

