#version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: javi98/python-api-crud-template:1.0.0
    container_name: python-api-crud-template-app
    restart: unless-stopped
    # command: fastapi run app/main.py --port 8000 # Production mode
    # command: fastapi run app/main.py --port 8000 --reload # Development mode
    ports:
      - 8000:8000
    volumes:
      - ./:/code
    depends_on:
      - db

  db:
    image: mariadb:11.2.2
    container_name: python-api-crud-template-db
    restart: unless-stopped
    env_file: .env.dev # .env.dev | .env.prod
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
 
volumes:
  db-data:
